### ISSUE TITLE
on article 6, cannot create a pokemon in cli

### ISSUE THREAD

**Issue by kennethinfante** [alexislozano/pokedex#2]
in command line and Git Bash, pressing shift when entering pokemon name skips the pokemon name.. also, pressing enter in the pokemon type results in "The request is invalid".

**Comment by alexislozano** [comment]
@kennethjhim Hi and thanks for telling me. This seems to be an issue of dialoguer: https://github.com/mitsuhiko/dialoguer/issues/110

**Comment by kennethinfante** [comment]
Hi Alexis. Got this. Updating the console package fixed this but the create_pokemon still does not work cause I can't select the appropriate type. Pressing enter after choosing Fire type returns an invalid request.

![issue1](https://user-images.githubusercontent.com/22592384/139753472-9ba9929b-3348-41d4-aa1b-98c94f30fe10.png)

**Comment by alexislozano** [comment]
@kennethjhim You have to select at least one type for the request to be valid. To select or unselect a type, you have to use the spacebar.

**Comment by kennethinfante** [comment]
Alright, thanks Alexis. Spacebar is the answer.haha :)
