### ISSUE TITLE
on article 7, fetching all pokemons result to 500 internal server error

### ISSUE THREAD

**Issue by kennethinfante** [alexislozano/pokedex#3]
the fetch all pokemon results to error but fetching individual pokemons is Ok

**Comment by alexislozano** [comment]
@kennethjhim Could you please give me some info to be able to reproduce? I've just cloned master and run `cargo run -- --cli`, I can create, fetch one, and fetch all pokemons. I'm on Linux. Maybe that's something with dialoguer as in #2? I cannot really test as I do not have a windows installation.

**Comment by kennethinfante** [comment]
Hi Alex, I'm referring to running with airtable. Fetching individual pokemon like http://localhost:8000/1 is ok but when using the base URL to fetch all pokemons, it is returning 500 internal error
![issue2](https://user-images.githubusercontent.com/22592384/139753087-690a9747-6995-4ce9-88cd-77a826a15ef5.png)

Same in cli
![issue3](https://user-images.githubusercontent.com/22592384/139753178-cda2e56f-de60-4b4e-9b18-a56f5b3d0109.png)

But when I try to query directly the airtable API using the request URL, it is working

![issue4](https://user-images.githubusercontent.com/22592384/139753381-883d0297-a4f8-4490-ace7-85cec7736bc5.png)

**Comment by alexislozano** [comment]
@kennethjhim In your last screenshot, the first record does not have any fields so the transformation to a pokemon won't work. Do you have empty lines in your airtable table? If yes, try to delete them :slightly_smiling_face:

**Comment by kennethinfante** [comment]
Thanks, Alexis. Deleting the blank rows solved it. By the way, what if I try to make it robust against the blank rows (cause as far as I remember, Airtable added the blank at the end), what code should I add?
I tried to change `_ => continue`  in the error path in the `fetch_all` code but that didn't work.

**Comment by alexislozano** [comment]
@kennethjhim You can try to do that, but for me it should still send back an error if one line is not empty but is not a valid Pokemon. For instance if you delete its name. The change should be done in `fetch_pokemon_rows` in `AirtableRepository`. This code:
```rs
match res.into_json::<AirtableJson>() {
    Ok(json) => Ok(json),
    _ => Err(()),
}
```
will have to changed.
